### ISSUE TITLE
Tried the example - ESP8266WiFi.h ERROR

### ISSUE THREAD

**Issue by Eisbaeeer** [aaronse/esp-iot-framework-examples#3]
Hi Aaronse
Now I found some time to test your examples. Out of the box compiling of the helloWorld example throw an error:

`.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/WiFiManager.cpp:5:10: fatal error: ESP8266WiFi.h: No such file or directory

*********************************************************************
* Looking for ESP8266WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESP8266WiFi.h"
* Web  > https://registry.platformio.org/search?q=header:ESP8266WiFi.h
*
*********************************************************************

 #include <ESP8266WiFi.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio\build\esp32dev\libcf1\ESP8266 IoT Framework\dashboard.cpp.o
*** [.pio\build\esp32dev\libcf1\ESP8266 IoT Framework\WiFiManager.cpp.o] Error 1
In file included from .pio/libdeps/esp32dev/ESP8266 IoT Framework/src/certStore.cpp:1:
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/certStore.h:9:10: fatal error: BearSSLHelpers.h: No such file or directory

************************************************************************
* Looking for BearSSLHelpers.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:BearSSLHelpers.h"
* Web  > https://registry.platformio.org/search?q=header:BearSSLHelpers.h
*
************************************************************************

 #include <BearSSLHelpers.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32dev\libcf1\ESP8266 IoT Framework\certStore.cpp.o] Error 1
In file included from .pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:4:
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.h:31:38: error: 'std::function' has not been declared
     void setConfigSaveCallback( std::function<void()> func );
                                      ^~~~~~~~
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.h:31:46: error: expected ',' or '...' before '<' token
     void setConfigSaveCallback( std::function<void()> func );
                                              ^
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.h:35:9: error: 'function' in namespace 'std' does not name a template type
    std::function<void()> _configsavecallback;
         ^~~~~~~~
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.h:35:4: note: 'std::function' is defined in header '<functional>'; did you forget to '#include <functional>'?        
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.h:6:1:
+#include <functional>

.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.h:35:4:
    std::function<void()> _configsavecallback;
    ^~~
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp: In member function 'void config::save()':
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:76:10: error: '_configsavecallback' was not declared in this scope
     if ( _configsavecallback != NULL) {
          ^~~~~~~~~~~~~~~~~~~
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:76:10: note: suggested alternative: 'setConfigSaveCallback'
     if ( _configsavecallback != NULL) {
          ^~~~~~~~~~~~~~~~~~~
          setConfigSaveCallback
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp: At global scope:
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:81:42: error: variable or field 'setConfigSaveCallback' declared void
 void config::setConfigSaveCallback( std::function<void()> func ) {
                                          ^~~~~~~~
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:81:42: error: 'function' is not a member of 'std'
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:81:42: note: 'std::function' is defined in header '<functional>'; did you forget to '#include <functional>'?     
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:5:1:
+#include <functional>

.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:81:42:
 void config::setConfigSaveCallback( std::function<void()> func ) {
                                          ^~~~~~~~
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:81:59: error: 'func' was not declared in this scope
 void config::setConfigSaveCallback( std::function<void()> func ) {
                                                           ^~~~
.pio/libdeps/esp32dev/ESP8266 IoT Framework/src/configManager.cpp:81:59: note: suggested alternative: 'fputc'
 void config::setConfigSaveCallback( std::function<void()> func ) {
                                                           ^~~~
                                                           fputc
*** [.pio\build\esp32dev\libcf1\ESP8266 IoT Framework\configManager.cpp.o] Error 1
=========================================================================== [FAILED] Took 19.36 seconds `

In platformio.ini I added your repo for framework:

`; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
board = esp32dev
platform = espressif32
lib_ldf_mode = deep
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    ESP Async WebServer
    ArduinoJson
    LittleFS_esp32
    Wire
    https://github.com/aaronse/esp8266-iot-framework
build_flags = -DCONFIG_PATH=src/configuration.json -DREBUILD_CONFIG -DREBUILD_HTML -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG

# preBuild.py script regenerates 1) HTML page (via webpack), 2) config objects, 3) Certificate store.
extra_scripts = lib/esp8266-iot-framework/scripts/preBuild.py
`

Any idea?
Greets Lars

**Comment by aaronse** [comment]
Hello @Eisbaeeer, haven't looked at this in a while, did you already try info in https://github.com/aaronse/esp-iot-framework-examples/issues/1#issuecomment-1054812634 and the posts that followed?

**Comment by Eisbaeeer** [comment]
Hi
Yes, I tried. I also done all steps a second time. Updated node.js and npm to newest version.
Run into the following error. Don´t touched anything in helloWorld demo.
`
> esp@1.0.0 build
> webpack --mode=production

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at iterateNormalLoaders (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\lars\OneDrive\Dokumente\PlatformIO\Projects\helloWorld\lib\esp8266-iot-framework\node_modules\babel-loader\lib\index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
Compiling .pio\build\esp32dev\lib3c1\esp8266-iot-framework\WiFiManager.cpp.o
Compiling .pio\build\esp32dev\lib3c1\esp8266-iot-framework\certStore.cpp.o
Compiling .pio\build\esp32dev\lib3c1\esp8266-iot-framework\configManager.cpp.o
Compiling .pio\build\esp32dev\lib3c1\esp8266-iot-framework\dashboard.cpp.o
Compiling .pio\build\esp32dev\lib3c1\esp8266-iot-framework\fetch.cpp.o
Compiling .pio\build\esp32dev\lib3c1\esp8266-iot-framework\generated\config.cpp.o
Compiling .pio\build\esp32dev\lib3c1\esp8266-iot-framework\timeSync.cpp.o
Compiling .pio\build\esp32dev\lib3c1\esp8266-iot-framework\updater.cpp.o
Compiling .pio\build\esp32dev\lib3c1\esp8266-iot-framework\webServer.cpp.o
Compiling .pio\build\esp32dev\src\helloWorld.cpp.o
Generating partitions .pio\build\esp32dev\partitions.bin
Compiling .pio\build\esp32dev\lib713\AsyncTCP\AsyncTCP.cpp.o
Compiling .pio\build\esp32dev\lib30b\FS\FS.cpp.o
Archiving .pio\build\esp32dev\lib713\libAsyncTCP.a
Compiling .pio\build\esp32dev\lib30b\FS\vfs_api.cpp.o
Compiling .pio\build\esp32dev\lib7ea\WiFi\WiFi.cpp.o
Compiling .pio\build\esp32dev\lib7ea\WiFi\WiFiAP.cpp.o
Compiling .pio\build\esp32dev\lib7ea\WiFi\WiFiClient.cpp.o
Archiving .pio\build\esp32dev\lib30b\libFS.a
Compiling .pio\build\esp32dev\lib7ea\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\esp32dev\lib7ea\WiFi\WiFiMulti.cpp.o
Compiling .pio\build\esp32dev\lib7ea\WiFi\WiFiSTA.cpp.o
Compiling .pio\build\esp32dev\lib7ea\WiFi\WiFiScan.cpp.o
Compiling .pio\build\esp32dev\lib7ea\WiFi\WiFiServer.cpp.o
Compiling .pio\build\esp32dev\lib7ea\WiFi\WiFiUdp.cpp.o
Compiling .pio\build\esp32dev\lib7e7\ESP Async WebServer\AsyncEventSource.cpp.o
Compiling .pio\build\esp32dev\lib7e7\ESP Async WebServer\AsyncWebSocket.cpp.o
Compiling .pio\build\esp32dev\lib7e7\ESP Async WebServer\SPIFFSEditor.cpp.o
Archiving .pio\build\esp32dev\lib7ea\libWiFi.a
Compiling .pio\build\esp32dev\lib7e7\ESP Async WebServer\WebAuthentication.cpp.o
Compiling .pio\build\esp32dev\lib7e7\ESP Async WebServer\WebHandlers.cpp.o
Compiling .pio\build\esp32dev\lib7e7\ESP Async WebServer\WebRequest.cpp.o
Compiling .pio\build\esp32dev\lib7e7\ESP Async WebServer\WebResponses.cpp.o
Compiling .pio\build\esp32dev\lib7e7\ESP Async WebServer\WebServer.cpp.o
Compiling .pio\build\esp32dev\lib576\LittleFS_esp32\LITTLEFS.cpp.o
Compiling .pio\build\esp32dev\lib576\LittleFS_esp32\esp_littlefs.c.o
Compiling .pio\build\esp32dev\lib576\LittleFS_esp32\lfs.c.o
.pio/libdeps/esp32dev/LittleFS_esp32/src/esp_littlefs.c:19:2: warning: #warning ("Use the built-in LITTLEFS library") [-Wcpp]
 #warning("Use the built-in LITTLEFS library")
  ^~~~~~~
.pio/libdeps/esp32dev/LittleFS_esp32/src/LITTLEFS.cpp: In member function 'virtual bool LITTLEFSImpl::exists(const char*)':
.pio/libdeps/esp32dev/LittleFS_esp32/src/LITTLEFS.cpp:44:28: error: no matching function for call to 'LITTLEFSImpl::open(const char*&, const char [2])'
     File f = open(path, "r");
                            ^
In file included from .pio/libdeps/esp32dev/LittleFS_esp32/src/LITTLEFS.cpp:17:
C:/Users/lars/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.h:38:17: note: candidate: 'virtual fs::FileImplPtr VFSImpl::open(const char*, const char*, bool)'
     FileImplPtr open(const char* path, const char* mode, const bool create) override;
                 ^~~~
C:/Users/lars/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.h:38:17: note:   candidate expects 3 arguments, 2 provided
*** [.pio\build\esp32dev\lib576\LittleFS_esp32\LITTLEFS.cpp.o] Error 1`
